name: Link to Trello
on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  #issues:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  attach-trello-pr:
    runs-on: ubuntu-latest
    name: Trello PR finding
    steps:
      - uses: kagof/trello-link-github-action@v1.1.0
        with:
          board-identifier: "${{ secrets.TRELLO_PR_CLOSED_LIST_ID }}"
          trello-token: "${{ secrets.TRELLO_TOKEN }}"
